global using PoeShared.Modularity;
global using PoeShared.Prism;
global using PoeShared.Scaffolding;
global using PropertyBinder;
global using ReactiveUI;
global using DynamicData;
global using System.Collections.Generic;
global using System.IO;
global using System.Net.Http;
global using System.Reactive.Concurrency;
global using System.Reactive.Linq;
global using System.Threading.Tasks;
global using Unity;
global using System;

global using FileInfo = System.IO.FileInfo;
global using Type = System.Type;
global using WinSize = System.Drawing.Size;
global using WinSizeF = System.Drawing.SizeF;
global using WinPoint = System.Drawing.Point;
global using WinPointF = System.Drawing.PointF;
global using WinRect = System.Drawing.Rectangle;
global using WinRectangle = System.Drawing.Rectangle;
global using WinRectangleF = System.Drawing.RectangleF;
global using WpfColor = System.Windows.Media.Color;
global using WinColor = System.Drawing.Color;

global using SharpColor = SixLabors.ImageSharp.Color;
global using SharpRectangle = SixLabors.ImageSharp.Rectangle;
global using SharpPoint = SixLabors.ImageSharp.Point;
global using SharpNumber = SixLabors.ImageSharp.Number;
global using SharpSize = SixLabors.ImageSharp.Size;
global using SharpRectangleF = SixLabors.ImageSharp.RectangleF;
global using SharpPointF = SixLabors.ImageSharp.PointF;
global using SharpSizeF = SixLabors.ImageSharp.SizeF;
global using SharpImage = SixLabors.ImageSharp.Image;